arch all 1
arch noarch 1
arch aarch64_a53 10      # 🔑 优先使用 Cortex-A53 优化包
arch aarch64_generic 20  # 🔑 次选通用 aarch64 包
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
# option check_signature
